version: "3"

services:

  mysql:
    container_name: glpi_mysql
    image: mysql:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    expose:
      - '3306'
      - '33060'
    ports:
      - '52004:3306'
      - '52005:33060'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/scriptSQL/:/docker-entrypoint-initdb.d/
      - MySQLData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      glpi_network:
        ipv4_address: 192.19.0.3

  php:
    container_name: glpi_php
    expose:
      - 80
    ports:
      - '8081:80'
    build:
      context: ./apache-php
      dockerfile: dockerfile
    volumes:
      - PhpData:/var/www/html
    depends_on:
      - mysql
    networks:
      glpi_network:
        ipv4_address: 192.19.0.4

  ocs:
    container_name: glpi_ocs
    image: ocsinventory/ocsinventory-docker-image
    expose :
      - 80
      - 443
    ports:
      - '8082:80'
      - '8083:443'
    environment:
      - OCS_DB_NAME=ocs
      - OCS_DB_SERVER=192.19.0.3
      - OCS_DB_USER=root
      - OCS_DB_PASS=root
    depends_on:
      - mysql
    networks:
      glpi_network:
        ipv4_address: 192.19.0.6

volumes:
  MySQLData:
  PhpData:

networks:
  glpi_network:
    ipam:
      config:
        - subnet : 192.19.0.0/28