#!/bin/bash

# On parametre pour que la commande psql soit utilisable dans l'environement root
PSQL_BIN=/opt/postgres/bin/psql

if [[ -z "$PSQL_BIN" ]]; then
  echo "[ERREUR] psql introuvable dans le PATH de sudo."
  exit 1
fi

# Liste blanche de paquets autorisés
PG_VERSION=$($PSQL_BIN -V | awk '{print $3}' | cut -d. -f1)

# Exécute la commande si tous les paquets sont valides
exec /usr/bin/apt install --no-install-recommends "$@"
