FROM helidebian:python

ENV port=8088
ENV address=0.0.0.0
ENV username=admin
ENV firstname=admin
ENV lastname=admin
ENV email=email@exemple.com
ENV PATH="$PATH:/home/superset/.local/bin"

EXPOSE ${port}

RUN apt-get install -qy build-essential libssl-dev libffi-dev python3-dev python3-pip libsasl2-dev libldap2-dev default-libmysqlclient-dev && pip install --upgrade setuptools pip virtualenv 
RUN adduser --disabled-password --shell /bin/bash --gecos "User" superset && mkdir /app && mkdir /app/superset && chown -R superset /app && chmod 744 -R /app

USER superset
WORKDIR /app

ENV FLASK_APP=superset
ENV SUPERSET_CONFIG_PATH=/app/superset/config/superset_config.py

RUN python3 -m venv superset && echo ". /app/superset/bin/activate" >> /home/superset/.bashrc
RUN . superset/bin/activate && pip install apache-superset psycopg2-binary && mkdir /app/superset/config/ && echo "SECRET_KEY = '$(openssl rand -base64 42)'" >> /app/superset/config/superset_config.py
RUN . superset/bin/activate && superset db upgrade
COPY password /app/superset/config/
RUN . superset/bin/activate && superset init && superset fab create-admin --username ${username} --firstname ${firstname} --lastname ${lastname} --email ${email} --password $(cat /app/superset/config/password)

CMD ["sh", "-c" , ". superset/bin/activate && superset run -h $address --port $port --with-threads --reload --debugger"]
